update Intl.LocaleMatcher, eraDisplay to stage 1, Intl.Locale info to stage 2
tc39/proposals pull request #335
Opened 2020-12-07 01:00 UTC by longlho

2020-12-07 06:28 UTC, ljharb requested changes

2020-12-07 06:28 UTC, ljharb commented on ecma402/README.md
> +- [Finished Proposals](finished-proposals.md)
i'll revert all these unrelated changes. please make sure your editor isn't blindly running prettier on all files - formatters should only run in projects that have them set up.

2020-12-07 06:31 UTC, ljharb commented
@longlho i'm confused; for localeMatcher to be at stage 1, a TC39 plenary must have occurred in which that gained consensus. 402 meetings do not have the capability of advancing stages. In which TC39 meeting did these advancements occur?

2020-12-07 14:02 UTC, longlho commented
Oh sry I didn't know that. We can ignore this PR then.

2020-12-07 16:05 UTC, septs commented
remove it?

2020-12-07 16:18 UTC, closed without merging

2020-12-09 09:36 UTC, septs commented
> remove it?

CC @ljharb

2020-12-10 08:09 UTC, ljharb commented
PRs can’t ever be deleted, nor generally would be even if it were possible, so I’m not sure why you’re cc’ing me.