Add update for Decimal
tc39/proposals pull request #495
Opened 2024-01-19 14:47 UTC by jessealama

Also, update the list of champions (it has changed since 2021).

2024-01-19 14:50 UTC, six-ponies commented
 
您好，您的邮件已收到，我将尽快给您回复。谢谢

2024-01-19 14:50 UTC, bzk1994 commented
你好，来信已收到

2024-01-19 18:22 UTC, ljharb requested changes

2024-01-19 18:22 UTC, ljharb commented on stage-1-proposals.md
> +| [Decimal][decimal]                                                                           | Daniel Ehrenberg<br />Andrew Paprocki                 | Andrew Paprocki<br />Jesse Alama<br />Jirka Ma
the link should be `decimal-notes`, and `decimal-stage-1-update-and-discussion` doesn't link anywhere (footnote links are at the bottom of the document). where should this link to?

2024-07-17 14:44 UTC, ljharb commented
@jessealama does the champions list not need to be updated?

2024-07-19 10:59 UTC, jessealama commented
> @jessealama does the champions list not need to be updated?

I'm not sure I understand?

2024-07-19 11:02 UTC, jessealama commented
> @jessealama does the champions list not need to be updated?

Ah, I see what you mean. Based on the title of the PR, I assumed this was a very stale change, adding a decimal presentation to the plenary agenda. But it isn't. I'll re-open this issue.

2025-04-17 16:17 UTC, ljharb commented
@jessealama can this be updated so it can be merged?

2025-09-25 13:51 UTC, jessealama commented
obsolete

2025-09-25 13:51 UTC, closed without merging