Withdraw array last
tc39/proposals pull request #511
Opened 2024-03-11 15:42 UTC by keithamus

Now Array#at is Stage 4, I see no reason to continue pursuing Array#lastItem. See the [README of the archived repo](https://github.com/tc39/proposal-array-last/):

> This proposal's champion (@keithamus) does not plan to advance to Stage 2 for now. Other proposals ([Array.prototype.item](https://github.com/tabatkins/proposal-item-method) and [Array Slice Notation](https://github.com/tc39/proposal-slice-notation)) also sufficiently solve this problem, and are advancing quicker through the standards track. Should one of these proposals advance to Stage 3, this proposal will be dropped.

2024-03-11 15:45 UTC, six-ponies commented
 
您好，您的邮件已收到，我将尽快给您回复。谢谢

2024-03-11 15:45 UTC, bzk1994 commented
你好，来信已收到

2024-03-11 15:54 UTC, linusg requested changes

2024-03-11 15:54 UTC, linusg commented on stage-1-proposals.md
> -| [Getting last element of Array][arraylast]                                                   | Keith Cirkel                                          | Keith Cirkel
`arraylast` and `arraylast-notes` link refs are no longer needed.

2024-03-11 17:23 UTC, ljharb approved these changes

2024-03-11 17:23 UTC, merged

2024-03-20 00:30 UTC, michaelficarra commented
It's customary to make an announcement at plenary for a withdrawal. @keithamus Do you think you could make that announcement or recruit someone to do so on your behalf?

2024-03-20 09:37 UTC, keithamus commented
Sure, can I recruit you @michaelficarra? :wink:

2024-03-20 15:21 UTC, ljharb commented
I’m happy to mention it.

2024-03-20 15:50 UTC, keithamus commented
Thanks @ljharb!